/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh;


import java.sql.ResultSet;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.processing.Messager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author USER
 */
public class AddAxis extends javax.swing.JFrame {
    /**
     * Creates new form RegisterMember
     */
    
    public String id;
    boolean check;

    public boolean isCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }
    public AddAxis() {
    initComponents();


        setSize(360,430);

    this.getContentPane().setBackground(new Color(209, 209, 224));
    this.setLocationRelativeTo(null);
    }
    public boolean checkInserting(AddAxis axis)
    {
        
        
        return isCheck();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRegister = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        cbBrandName = new javax.swing.JComboBox<>();
        lbAdd = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        txtMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        txtPrice2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(92, 92, 138));
        setUndecorated(true);
        setOpacity(0.95F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegister.setBackground(new java.awt.Color(51, 51, 51));
        panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "INSERTING", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(255, 255, 102))); // NOI18N
        panelRegister.setPreferredSize(new java.awt.Dimension(250, 530));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(153, 153, 255));
        txtQuantity.setText("XAxis");
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtQuantity.setCaretColor(new java.awt.Color(102, 0, 102));
        txtQuantity.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        panelRegister.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 280, 50));

        cbBrandName.setBackground(new java.awt.Color(255, 255, 255));
        cbBrandName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbBrandName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        panelRegister.add(cbBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 50));

        lbAdd.setFont(new java.awt.Font("VNI-Cooper", 1, 20)); // NOI18N
        lbAdd.setForeground(new java.awt.Color(255, 255, 102));
        lbAdd.setText("ADD");
        lbAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddMouseClicked(evt);
            }
        });
        panelRegister.add(lbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 140, 30));

        btAdd.setBackground(new java.awt.Color(102, 102, 102));
        btAdd.setForeground(new java.awt.Color(255, 255, 0));
        btAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btAdd.setBorder(null);
        btAdd.setBorderPainted(false);
        btAdd.setContentAreaFilled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        panelRegister.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 180, 70));

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(153, 153, 255));
        txtPrice.setText("YAxis");
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });
        panelRegister.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 50));

        txtMinimize.setBackground(new java.awt.Color(51, 51, 51));
        txtMinimize.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtMinimize.setForeground(new java.awt.Color(255, 255, 102));
        txtMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinimize.setText("-");
        txtMinimize.setOpaque(true);
        txtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseExited(evt);
            }
        });
        panelRegister.add(txtMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 30, 20));

        txtExit.setBackground(new java.awt.Color(51, 51, 51));
        txtExit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 102));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setOpaque(true);
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        panelRegister.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 20));

        txtPrice1.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice1.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtPrice1.setForeground(new java.awt.Color(153, 153, 255));
        txtPrice1.setText("YAxis");
        txtPrice1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPrice1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrice1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrice1FocusLost(evt);
            }
        });
        panelRegister.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 50));

        txtPrice2.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice2.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtPrice2.setForeground(new java.awt.Color(153, 153, 255));
        txtPrice2.setText("WIDTH");
        txtPrice2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtPrice2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrice2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrice2FocusLost(evt);
            }
        });
        panelRegister.add(txtPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, 50));

        jLabel1.setText("jLabel1");
        panelRegister.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, 50));

        getContentPane().add(panelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
                 
    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        // TODO add your handling code here:
            if(txtQuantity.getText().trim().toUpperCase().equals("QUANTITY*"))
            {
           txtQuantity.setFont(new Font("Dialog", Font.BOLD, 16));
           txtQuantity.setForeground(new Color(10, 15, 15));
           txtQuantity.setText("");
               }
    }//GEN-LAST:event_txtQuantityFocusGained

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:
             if(txtQuantity.getText().trim().toUpperCase().equals(""))
               {
           txtQuantity.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtQuantity.setForeground(new Color(51,51,51));
           txtQuantity.setText("QUANTITY*"); 
               }
    }//GEN-LAST:event_txtQuantityFocusLost
    
    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        // TODO add your handling code here:
                    if(txtPrice.getText().trim().toUpperCase().equals("PRICE*"))
                  {
           txtPrice.setFont(new Font("Dialog", Font.BOLD, 16));
           txtPrice.setForeground(new Color(10, 15, 15));
           txtPrice.setText("");
                  }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        // TODO add your handling code here:
                    if(txtPrice.getText().trim().toUpperCase().equals(""))
               {
           txtPrice.setFont(new Font("Dubai Light", Font.ITALIC, 16));
           txtPrice.setForeground(new Color(51,51,51));
           txtPrice.setText("PRICE*"); 
               }
        
    }//GEN-LAST:event_txtPriceFocusLost

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btAddActionPerformed

    private void txtMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseExited
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtMinimizeMouseExited

    private void txtMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseEntered
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(200, 0,0));
    }//GEN-LAST:event_txtMinimizeMouseEntered

    private void txtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_txtMinimizeMouseClicked

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(new Color(200, 0,0));
        
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_txtExitMouseExited

    private void lbAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddMouseClicked
        // TODO add your handling code here:
        txtPrice.setLocation(50, 50);
    }//GEN-LAST:event_lbAddMouseClicked

    private void txtPrice1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice1FocusGained

    private void txtPrice1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice1FocusLost

    private void txtPrice2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2FocusGained

    private void txtPrice2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2FocusLost

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAxis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbBrandName;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lbAdd;
    public javax.swing.JPanel panelRegister;
    public javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtMinimize;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtPrice1;
    public javax.swing.JTextField txtPrice2;
    public javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
