/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class DetailAxis extends javax.swing.JFrame {

    int n;

    public int getN() {
        return n;
    }

    public void setN(int n) {
        this.n = n;
    }
    /**
     * Creates new form DetailAxis
     */
    public DetailAxis() {   
        initComponents();
        this.getContentPane().setBackground(new Color(255,240,230));
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetail = new javax.swing.JPanel();
        lbTopic1 = new javax.swing.JLabel();
        lbTopic1Content1 = new javax.swing.JLabel();
        lbTopic1Content3 = new javax.swing.JLabel();
        lbTopic1Content2 = new javax.swing.JLabel();
        lbTopic2 = new javax.swing.JLabel();
        lbTopic2Content1 = new javax.swing.JLabel();
        lbTopic2Content2 = new javax.swing.JLabel();
        lbTopic2Content3 = new javax.swing.JLabel();
        lbTopic3 = new javax.swing.JLabel();
        lbTopic3Content1 = new javax.swing.JLabel();
        lbTopic3Content2 = new javax.swing.JLabel();
        lbTopic3Content3 = new javax.swing.JLabel();
        txtMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 240, 230));
        setUndecorated(true);

        panelDetail.setBackground(new java.awt.Color(255, 240, 230));
        panelDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTopic1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTopic1.setForeground(new java.awt.Color(51, 0, 0));
        panelDetail.add(lbTopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, 43));
        panelDetail.add(lbTopic1Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 30));
        panelDetail.add(lbTopic1Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 310, 30));
        panelDetail.add(lbTopic1Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 30));

        lbTopic2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTopic2.setForeground(new java.awt.Color(51, 0, 0));
        panelDetail.add(lbTopic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 43));
        panelDetail.add(lbTopic2Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 310, 30));
        panelDetail.add(lbTopic2Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 310, 30));
        panelDetail.add(lbTopic2Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, 30));

        lbTopic3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTopic3.setForeground(new java.awt.Color(51, 0, 0));
        panelDetail.add(lbTopic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 280, 43));
        panelDetail.add(lbTopic3Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 310, 30));
        panelDetail.add(lbTopic3Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 310, 30));
        panelDetail.add(lbTopic3Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 310, 30));

        txtMinimize.setBackground(new java.awt.Color(255, 240, 230));
        txtMinimize.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtMinimize.setForeground(new java.awt.Color(204, 204, 0));
        txtMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinimize.setText("-");
        txtMinimize.setOpaque(true);
        txtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseExited(evt);
            }
        });

        txtExit.setBackground(new java.awt.Color(255, 240, 230));
        txtExit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtExit.setForeground(new java.awt.Color(204, 204, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setOpaque(true);
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtExit)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_txtMinimizeMouseClicked

    private void txtMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseEntered
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(200, 0,0));
        txtMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_txtMinimizeMouseEntered

    private void txtMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseExited
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(255,240,230));
        txtMinimize.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_txtMinimizeMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(new Color(200, 0,0));

    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(255,240,230));
        txtExit.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_txtExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailAxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailAxis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbTopic1;
    public javax.swing.JLabel lbTopic1Content1;
    public javax.swing.JLabel lbTopic1Content2;
    public javax.swing.JLabel lbTopic1Content3;
    public javax.swing.JLabel lbTopic2;
    public javax.swing.JLabel lbTopic2Content1;
    public javax.swing.JLabel lbTopic2Content2;
    public javax.swing.JLabel lbTopic2Content3;
    public javax.swing.JLabel lbTopic3;
    public javax.swing.JLabel lbTopic3Content1;
    public javax.swing.JLabel lbTopic3Content2;
    public javax.swing.JLabel lbTopic3Content3;
    public javax.swing.JPanel panelDetail;
    public javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtMinimize;
    // End of variables declaration//GEN-END:variables
}
