/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh;
import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;


public class MainFrame extends javax.swing.JFrame {
    Thread t;
    int xx;
    int xy;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Image img=new ImageIcon("MeoMeoLogo.png").getImage().getScaledInstance(600, 400, Image.SCALE_SMOOTH);
        lbLoGo1.setIcon(new ImageIcon(img));
        Image img1=new ImageIcon("logo4.png").getImage().getScaledInstance(300, 200, Image.SCALE_SMOOTH);
//        lbLogo2.setIcon(new ImageIcon(img1));
     

        this.setLocationRelativeTo(null);
       
        lb3DBoxy.setVisible(false);
        lb3DSphere.setVisible(false);
        panelText.setLayout(null);
        panelContent.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        lb2DEgg = new javax.swing.JLabel();
        lb2DView = new javax.swing.JLabel();
        lb3DBoxy = new javax.swing.JLabel();
        lb3DSphere = new javax.swing.JLabel();
        panelText = new javax.swing.JPanel();
        panel2DBar = new javax.swing.JPanel();
        lb2DShape = new javax.swing.JLabel();
        lb3DShape = new javax.swing.JLabel();
        panelSideBar = new javax.swing.JPanel();
        lbLoGo = new javax.swing.JLabel();
        lbLoGo1 = new javax.swing.JLabel();
        lbMinisize = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setBackground(new java.awt.Color(51, 51, 51));
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb2DEgg.setBackground(new java.awt.Color(255, 255, 255));
        lb2DEgg.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb2DEgg.setForeground(new java.awt.Color(255, 255, 255));
        lb2DEgg.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\KTDH\\bird128.png")); // NOI18N
        lb2DEgg.setText("EGG & CHICK");
        lb2DEgg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2DEggMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb2DEggMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb2DEggMouseExited(evt);
            }
        });
        panelContent.add(lb2DEgg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 270, 140));

        lb2DView.setBackground(new java.awt.Color(255, 255, 255));
        lb2DView.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb2DView.setForeground(new java.awt.Color(255, 255, 255));
        lb2DView.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\KTDH\\mountain128.png")); // NOI18N
        lb2DView.setText("VIEW");
        lb2DView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2DViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb2DViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb2DViewMouseExited(evt);
            }
        });
        panelContent.add(lb2DView, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 210, 112));

        lb3DBoxy.setBackground(new java.awt.Color(255, 255, 255));
        lb3DBoxy.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb3DBoxy.setForeground(new java.awt.Color(255, 255, 255));
        lb3DBoxy.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\KTDH\\geometry.png")); // NOI18N
        lb3DBoxy.setText("BOXY");
        lb3DBoxy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3DBoxyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb3DBoxyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb3DBoxyMouseExited(evt);
            }
        });
        panelContent.add(lb3DBoxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 207, 140));

        lb3DSphere.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb3DSphere.setForeground(new java.awt.Color(255, 255, 255));
        lb3DSphere.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\KTDH\\cube.png")); // NOI18N
        lb3DSphere.setText("SPHERE");
        lb3DSphere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3DSphereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb3DSphereMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb3DSphereMouseExited(evt);
            }
        });
        panelContent.add(lb3DSphere, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 240, 130));

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1000, 330));

        panelText.setBackground(new java.awt.Color(51, 51, 51));

        panel2DBar.setBackground(new java.awt.Color(153, 153, 0));
        panel2DBar.setPreferredSize(new java.awt.Dimension(127, 4));

        javax.swing.GroupLayout panel2DBarLayout = new javax.swing.GroupLayout(panel2DBar);
        panel2DBar.setLayout(panel2DBarLayout);
        panel2DBarLayout.setHorizontalGroup(
            panel2DBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        panel2DBarLayout.setVerticalGroup(
            panel2DBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        lb2DShape.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lb2DShape.setForeground(new java.awt.Color(255, 255, 255));
        lb2DShape.setText("2D SHAPE");
        lb2DShape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2DShapeMouseClicked(evt);
            }
        });

        lb3DShape.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lb3DShape.setForeground(new java.awt.Color(255, 255, 255));
        lb3DShape.setText("3D SHAPE");
        lb3DShape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3DShapeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTextLayout = new javax.swing.GroupLayout(panelText);
        panelText.setLayout(panelTextLayout);
        panelTextLayout.setHorizontalGroup(
            panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextLayout.createSequentialGroup()
                .addGroup(panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTextLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lb2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lb3DShape))
                    .addGroup(panelTextLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(panel2DBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(660, Short.MAX_VALUE))
        );
        panelTextLayout.setVerticalGroup(
            panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextLayout.createSequentialGroup()
                .addGroup(panelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb2DShape, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lb3DShape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2DBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel2DBar.getAccessibleContext().setAccessibleName("");

        getContentPane().add(panelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 990, 70));

        panelSideBar.setBackground(new java.awt.Color(51, 51, 51));
        panelSideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSideBarMouseDragged(evt);
            }
        });
        panelSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSideBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelSideBarMouseReleased(evt);
            }
        });
        panelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelSideBar.add(lbLoGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 350, 160));
        panelSideBar.add(lbLoGo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 560, 260));

        lbMinisize.setBackground(new java.awt.Color(51, 51, 51));
        lbMinisize.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbMinisize.setForeground(new java.awt.Color(255, 255, 255));
        lbMinisize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMinisize.setText("-");
        lbMinisize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinisizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMinisizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMinisizeMouseExited(evt);
            }
        });
        panelSideBar.add(lbMinisize, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, 30));

        lbClose.setBackground(new java.awt.Color(51, 51, 51));
        lbClose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbClose.setForeground(new java.awt.Color(255, 255, 255));
        lbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClose.setText("X");
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCloseMouseExited(evt);
            }
        });
        panelSideBar.add(lbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 50, 30));

        getContentPane().add(panelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSideBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSideBarMouseReleased
        // TODO add your handling code here:
        this.setOpacity((float)1.0);
    }//GEN-LAST:event_panelSideBarMouseReleased

    private void panelSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSideBarMousePressed
        // TODO add your handling code here:
        this.setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_panelSideBarMousePressed

    private void panelSideBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSideBarMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_panelSideBarMouseDragged

    private void lb2DShapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DShapeMouseClicked
        // TODO add your handling code here:
        int y=panel2DBar.getY();
        int w=panel2DBar.getWidth();
        int h=panel2DBar.getHeight();
        for(int x=217;x>=40;x-=5)
        {
                panel2DBar.setVisible(false);
                panel2DBar.setBounds(x, y, w, h);
                panel2DBar.setVisible(true);
        }
        lb2DEgg.setVisible(true);
        lb2DView.setVisible(true);
        lb3DBoxy.setVisible(false);
        lb3DSphere.setVisible(false);
    }//GEN-LAST:event_lb2DShapeMouseClicked

    private void lb3DShapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DShapeMouseClicked
        // TODO add your handling code here:
        int y=panel2DBar.getY();
        int w=panel2DBar.getWidth();
        int h=panel2DBar.getHeight();
        for(int x=10;x<=217;x+=5)
        {

                panel2DBar.setVisible(false);
                panel2DBar.setBounds(x, y, w, h);
                panel2DBar.setVisible(true);

        }
        lb2DEgg.setVisible(false);
        lb2DView.setVisible(false);
        lb3DBoxy.setVisible(true);
        lb3DSphere.setVisible(true);
    }//GEN-LAST:event_lb3DShapeMouseClicked

    private void lb2DEggMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DEggMouseEntered
        // TODO add your handling code here:
        lb2DEgg.setForeground(Color.yellow);
    }//GEN-LAST:event_lb2DEggMouseEntered

    private void lb2DViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DViewMouseExited
        // TODO add your handling code here:
       
        lb2DView.setForeground(Color.white);
    }//GEN-LAST:event_lb2DViewMouseExited

    private void lb2DViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DViewMouseEntered
        // TODO add your handling code here:
        lb2DView.setForeground(Color.yellow);
        
    }//GEN-LAST:event_lb2DViewMouseEntered

    private void lb2DEggMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DEggMouseExited
        // TODO add your handling code here:
         lb2DEgg.setForeground(Color.white);
    }//GEN-LAST:event_lb2DEggMouseExited

    private void lb3DBoxyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DBoxyMouseEntered
        // TODO add your handling code here:
        lb3DBoxy.setForeground(Color.yellow);
    }//GEN-LAST:event_lb3DBoxyMouseEntered

    private void lb3DBoxyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DBoxyMouseExited
        // TODO add your handling code here:
         lb3DBoxy.setForeground(Color.white);
    }//GEN-LAST:event_lb3DBoxyMouseExited

    private void lb3DSphereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DSphereMouseEntered
        // TODO add your handling code here:
        lb3DSphere.setForeground(Color.yellow);
    }//GEN-LAST:event_lb3DSphereMouseEntered

    private void lb3DSphereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DSphereMouseExited
        // TODO add your handling code here:
        lb3DSphere.setForeground(Color.white);
    }//GEN-LAST:event_lb3DSphereMouseExited

    private void lb2DEggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DEggMouseClicked
        // TODO add your handling code here:
         t=new Thread(new Runnable() {
            @Override
            public void run() {
               new Egg().go();
            }
        });
        t.start();
        
    }//GEN-LAST:event_lb2DEggMouseClicked

    private void lbMinisizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinisizeMouseExited
        // TODO add your handling code here:
        lbMinisize.setForeground(Color.white);
        lbMinisize.setBackground(new Color(51,51,51));
        
    }//GEN-LAST:event_lbMinisizeMouseExited

    private void lbMinisizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinisizeMouseEntered
        // TODO add your handling code here:
        lbMinisize.setForeground(Color.yellow);
        lbMinisize.setBackground(Color.red);
        lbMinisize.setOpaque(true);
    }//GEN-LAST:event_lbMinisizeMouseEntered

    private void lbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseEntered
        // TODO add your handling code here:
        lbClose.setForeground(Color.yellow);
        lbClose.setBackground(Color.red);
        lbClose.setOpaque(true);
    }//GEN-LAST:event_lbCloseMouseEntered

    private void lbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseExited
        // TODO add your handling code here:
        lbClose.setForeground(Color.white);
        lbClose.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_lbCloseMouseExited

    private void lbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbCloseMouseClicked

    private void lbMinisizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinisizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED) ;
    }//GEN-LAST:event_lbMinisizeMouseClicked

    private void lb2DViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2DViewMouseClicked
        // TODO add your handling code here:
      
                 t=new Thread(new Runnable() {
            @Override
            public void run() {
               new View2_1().go();
            }
        });
        t.start();
        
        
    }//GEN-LAST:event_lb2DViewMouseClicked

    private void lb3DBoxyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DBoxyMouseClicked
        // TODO add your handling code here:
        Boxy bx=new Boxy();
        bx.setVisible(true);
    }//GEN-LAST:event_lb3DBoxyMouseClicked

    private void lb3DSphereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3DSphereMouseClicked
        // TODO add your handling code here:
        Sphere cb=new Sphere();
        cb.setVisible(true);
    }//GEN-LAST:event_lb3DSphereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb2DEgg;
    private javax.swing.JLabel lb2DShape;
    private javax.swing.JLabel lb2DView;
    private javax.swing.JLabel lb3DBoxy;
    private javax.swing.JLabel lb3DShape;
    private javax.swing.JLabel lb3DSphere;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbLoGo;
    private javax.swing.JLabel lbLoGo1;
    private javax.swing.JLabel lbMinisize;
    private javax.swing.JPanel panel2DBar;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSideBar;
    private javax.swing.JPanel panelText;
    // End of variables declaration//GEN-END:variables
}
