/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author USER
 */
public class Sphere extends javax.swing.JFrame {
   int color=0;
   int x=1,y=1,z=1, w=1;
// String color;

    /**
     * Creates new form NewJFrame
     */
    
//      COLOR CODE
//0: Black
//1: Blue
//2: green
//3: cyan
//4: red
//5: Magenta
//6: Light Gray
//7: darkgray
//8: yellow
//9: white
//10:Organge
//11:pink
//12: Gray
//13: Browns
 //14: Nước biển
 //15: Màu mây
//16: Dòng chảy
//17: NÚI TÔNG NHẸ 2
//18: NÚI TÔNG NHẸ 1
//19: NÚI TÔNG NHẸ 0
//20: MÀU NẮNG  
    
    
    public Sphere() {
       DrawingAlogithrm a=new DrawingAlogithrm();
        initComponents();
        this.setSize(1150, 600);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(255, 240, 230));
        ArrayList<String> arrColor=new ArrayList<>();
        arrColor.add("BLACK");
        arrColor.add("BLUE");
        arrColor.add("GREEN");
        arrColor.add("RED");
        arrColor.add("CYAN"); arrColor.add("YELLOW");
        arrColor.add("ORGANGE"); arrColor.add("PINK");
        arrColor.add("GRAY");arrColor.add("BROWN");
        for(String i:arrColor)
        {
            cbColor.addItem(i);
        }
        AutoCompleteDecorator.decorate(cbColor);
        //lbColor.setIcon(new ImageIcon("black.png"));
        
        
    }
    public boolean checkCube(String xAxis,String yAxis,String zAxis,String width)
    {
        boolean check=true;
        boolean checkXAxis=true;
        boolean checkYAxis=true;
         boolean checkZAxis=true;
        boolean checkWidth=true;
        for (int i=0;i<xAxis.length();i++)
       {
         if(i==0)
         {
           if(xAxis.charAt(0)==45 )
           {
               checkXAxis=true;
              
           }
         }
         else
         {
           if (xAxis.charAt(i)<48 || xAxis.charAt(i)>57)
           {
               checkXAxis=false;
               break;
           }
         }
       }
       //CHECK Y
   
             for (int i=0;i<yAxis.length();i++)
            {
                if(i==0)
                {
                       if(yAxis.charAt(0)==45 )
                       {
                           checkYAxis=true;

                       }
                }
                else
                {
                    if(yAxis.charAt(i)<48 || yAxis.charAt(i)>57)
                   {
                       checkYAxis=false;
                       break;
                   }
                }
             }
            // CHECK Z
            for (int i=0;i<zAxis.length();i++)
            {
                if(i==0)
                {
                        if(zAxis.charAt(0)==45 )
                   {
                       checkZAxis=true;

                   }
                }
                else
                {
                    if(zAxis.charAt(i)<48 || zAxis.charAt(i)>57)
                    {
                        checkZAxis=false;
                        break;
                    }
                }
             }
             
           
        //CHECK WIDTH     
       
            for (int i=0;i<width.length();i++)
            {
           if(width.charAt(i)<48 || width.charAt(i)>57)
               {
               checkWidth=false;
               break;
               }
            }
       

          

            
            if(checkXAxis==false)
            {
                check=false;
                JOptionPane.showMessageDialog(null, "X IS NOT VALID","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else if(checkYAxis==false)
            {
                JOptionPane.showMessageDialog(null, "Y IS NOT VALID","ERROR",JOptionPane.ERROR_MESSAGE);
                 check=false;
            }
            else if(checkWidth==false)
            {
               JOptionPane.showMessageDialog(null, "WIDTH IS NOT VALID","ERROR",JOptionPane.ERROR_MESSAGE);
                 check=false;
            }

 
       
        return check;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegister = new javax.swing.JPanel();
        txtXAxis = new javax.swing.JTextField();
        cbColor = new javax.swing.JComboBox<>();
        lbAdd = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        txtMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        txtYAxis = new javax.swing.JTextField();
        txtRadius = new javax.swing.JTextField();
        lbColor = new javax.swing.JLabel();
        txtZAxis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        panelRegister.setBackground(new java.awt.Color(255, 240, 230));
        panelRegister.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "INSERTING", javax.swing.border.TitledBorder.ABOVE_TOP, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Dialog", 1, 21), new java.awt.Color(128, 102, 0)));
        panelRegister.setPreferredSize(new java.awt.Dimension(250, 530));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtXAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtXAxis.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtXAxis.setForeground(new java.awt.Color(153, 153, 255));
        txtXAxis.setText("XAXIS");
        txtXAxis.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtXAxis.setCaretColor(new java.awt.Color(102, 0, 102));
        txtXAxis.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtXAxis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtXAxisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXAxisFocusLost(evt);
            }
        });
        txtXAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtXAxisKeyPressed(evt);
            }
        });
        panelRegister.add(txtXAxis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 50));

        cbColor.setBackground(new java.awt.Color(255, 255, 255));
        cbColor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbColor.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        cbColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbColorItemStateChanged(evt);
            }
        });
        panelRegister.add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 50));

        lbAdd.setFont(new java.awt.Font("VNI-Cooper", 1, 20)); // NOI18N
        lbAdd.setForeground(new java.awt.Color(255, 255, 102));
        lbAdd.setText("DRAW");
        lbAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddMouseClicked(evt);
            }
        });
        panelRegister.add(lbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 80, 40));

        btAdd.setBackground(new java.awt.Color(102, 102, 102));
        btAdd.setForeground(new java.awt.Color(255, 255, 0));
        btAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\Môn Lớp\\Kĩ Thuật phần mềm\\button.png")); // NOI18N
        btAdd.setBorder(null);
        btAdd.setBorderPainted(false);
        btAdd.setContentAreaFilled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        panelRegister.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 180, 70));

        txtMinimize.setBackground(new java.awt.Color(255, 240, 230));
        txtMinimize.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txtMinimize.setForeground(new java.awt.Color(204, 204, 0));
        txtMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMinimize.setText("-");
        txtMinimize.setOpaque(true);
        txtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMinimizeMouseExited(evt);
            }
        });
        panelRegister.add(txtMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 20, 20));

        txtExit.setBackground(new java.awt.Color(255, 240, 230));
        txtExit.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtExit.setForeground(new java.awt.Color(204, 204, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("x");
        txtExit.setOpaque(true);
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });
        panelRegister.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 20));

        txtYAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtYAxis.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtYAxis.setForeground(new java.awt.Color(153, 153, 255));
        txtYAxis.setText("YAXIS");
        txtYAxis.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtYAxis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtYAxisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYAxisFocusLost(evt);
            }
        });
        txtYAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYAxisKeyPressed(evt);
            }
        });
        panelRegister.add(txtYAxis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 50));

        txtRadius.setBackground(new java.awt.Color(255, 255, 255));
        txtRadius.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtRadius.setForeground(new java.awt.Color(153, 153, 255));
        txtRadius.setText("RADIUS");
        txtRadius.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtRadius.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRadiusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRadiusFocusLost(evt);
            }
        });
        txtRadius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRadiusKeyPressed(evt);
            }
        });
        panelRegister.add(txtRadius, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, 50));

        lbColor.setBackground(new java.awt.Color(0, 0, 0));
        lbColor.setOpaque(true);
        panelRegister.add(lbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 70, 50));

        txtZAxis.setBackground(new java.awt.Color(255, 255, 255));
        txtZAxis.setFont(new java.awt.Font("Segoe Print", 2, 16)); // NOI18N
        txtZAxis.setForeground(new java.awt.Color(153, 153, 255));
        txtZAxis.setText("ZAXIS");
        txtZAxis.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        txtZAxis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtZAxisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZAxisFocusLost(evt);
            }
        });
        txtZAxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtZAxisKeyPressed(evt);
            }
        });
        panelRegister.add(txtZAxis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 854, Short.MAX_VALUE)
                .addComponent(panelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtXAxisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXAxisFocusGained
        // TODO add your handling code here:
        if(txtXAxis.getText().trim().toUpperCase().equals("XAXIS"))
        {
            txtXAxis.setFont(new Font("Dialog", Font.BOLD, 16));
            txtXAxis.setForeground(new Color(10, 15, 15));
            txtXAxis.setText("");
        }
    }//GEN-LAST:event_txtXAxisFocusGained

    private void txtXAxisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXAxisFocusLost
        // TODO add your handling code here:
        if(txtXAxis.getText().trim().toUpperCase().equals(""))
        {
            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
            txtXAxis.setForeground(new Color(153,153,255));
            txtXAxis.setText("XAXIS");
        }
    }//GEN-LAST:event_txtXAxisFocusLost

    private void lbAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddMouseClicked
        // TODO add your handling code here:
  
        
        if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                  x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }
        
    }//GEN-LAST:event_lbAddMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
             if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                 x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }

    }//GEN-LAST:event_btAddActionPerformed

    private void txtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseClicked
        // TODO add your handling code here:
        setState(this.ICONIFIED);
    }//GEN-LAST:event_txtMinimizeMouseClicked

    private void txtMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseEntered
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(200, 0,0));
         txtMinimize.setForeground(Color.yellow);
    }//GEN-LAST:event_txtMinimizeMouseEntered

    private void txtMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinimizeMouseExited
        // TODO add your handling code here:
        txtMinimize.setBackground(new Color(255,240,230));
        txtMinimize.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_txtMinimizeMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(new Color(200, 0,0));
        

    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(255,240,230));
        txtExit.setForeground(new Color(204,204,0));
    }//GEN-LAST:event_txtExitMouseExited

    private void txtYAxisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYAxisFocusGained
        // TODO add your handling code here:
         if(txtYAxis.getText().trim().toUpperCase().equals("YAXIS"))
        {
            txtYAxis.setFont(new Font("Dialog", Font.BOLD, 16));
            txtYAxis.setForeground(new Color(10, 15, 15));
            txtYAxis.setText("");
        }
    }//GEN-LAST:event_txtYAxisFocusGained

    private void txtYAxisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYAxisFocusLost
        // TODO add your handling code here:
        if(txtYAxis.getText().trim().toUpperCase().equals(""))
        {
            txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
            txtYAxis.setForeground(new Color(153,153,255));
            txtYAxis.setText("YAXIS");
        }
    }//GEN-LAST:event_txtYAxisFocusLost

    private void txtRadiusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadiusFocusGained
        // TODO add your handling code here:
        if(txtRadius.getText().trim().toUpperCase().equals("RADIUS"))
        {
            txtRadius.setFont(new Font("Dialog", Font.BOLD, 16));
            txtRadius.setForeground(new Color(10, 15, 15));
            txtRadius.setText("");
        }
        
    }//GEN-LAST:event_txtRadiusFocusGained

    private void txtRadiusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadiusFocusLost
        // TODO add your handling code here:
        if(txtRadius.getText().trim().toUpperCase().equals(""))
        {
            txtRadius.setFont(new Font("Segoe Print", Font.ITALIC, 16));
            txtRadius.setForeground(new Color(153,153,255));
            txtRadius.setText("RADIUS");
        }
    }//GEN-LAST:event_txtRadiusFocusLost

    private void cbColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbColorItemStateChanged
        // TODO add your handling code here:
        if(String.valueOf(cbColor.getEditor().getItem()).equals("BLACK"))
        {
           lbColor.setBackground(Color.black);
           color=0;
        }
        else if(String.valueOf(cbColor.getEditor().getItem()).equals("BLUE"))
        {
           lbColor.setBackground(Color.blue);
           color=1;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("GREEN"))
        {
           lbColor.setBackground(Color.GREEN);  
           color=2;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("RED"))
        {
           lbColor.setBackground(Color.red);
           color=4;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("CYAN"))
        {
           lbColor.setBackground(Color.cyan);
           color=3;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("YELLOW"))
        {
           lbColor.setBackground(Color.yellow);
           color=8;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("ORGANGE"))
        {
           lbColor.setBackground(Color.orange);
           color=10;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("PINK"))
        {
           lbColor.setBackground(Color.PINK);
           color=11;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("GRAY"))
        {
           lbColor.setBackground(Color.GRAY);
           color=7;
        }
         else if(String.valueOf(cbColor.getEditor().getItem()).equals("BROWN"))
        {
           lbColor.setBackground(new Color(77, 38, 0));
           color=13;
        }
    }//GEN-LAST:event_cbColorItemStateChanged

    private void txtRadiusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadiusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                 x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }
        }
    }//GEN-LAST:event_txtRadiusKeyPressed

    private void txtYAxisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYAxisKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                  x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }
        }
    }//GEN-LAST:event_txtYAxisKeyPressed

    private void txtXAxisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXAxisKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                  x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }
        }
    }//GEN-LAST:event_txtXAxisKeyPressed

    private void txtZAxisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZAxisFocusGained
        // TODO add your handling code here:
         if(txtZAxis.getText().trim().toUpperCase().equals("ZAXIS"))
        {
            txtZAxis.setFont(new Font("Dialog", Font.BOLD, 16));
            txtZAxis.setForeground(new Color(10, 15, 15));
            txtZAxis.setText("");
        }
       
    }//GEN-LAST:event_txtZAxisFocusGained

    private void txtZAxisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZAxisFocusLost
        // TODO add your handling code here:
          if(txtZAxis.getText().trim().toUpperCase().equals(""))
        {
            txtZAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
            txtZAxis.setForeground(new Color(153,153,255));
            txtZAxis.setText("ZAXIS");
        }
    }//GEN-LAST:event_txtZAxisFocusLost

    private void txtZAxisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZAxisKeyPressed
        // TODO add your handling code here:
                 if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
             if(checkCube(txtXAxis.getText(), txtYAxis.getText(),txtZAxis.getText(), txtRadius.getText())==true)
        {
                x=Integer.parseInt(txtXAxis.getText());
                y=Integer.parseInt(txtYAxis.getText());
                z=Integer.parseInt(txtZAxis.getText());
                w=Integer.parseInt(txtRadius.getText());
//        // SET LẠI BAN ĐẦU
//            txtXAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtXAxis.setForeground(new Color(153,153,255));
//            txtXAxis.setText("XAXIS");
//            
//             txtYAxis.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtYAxis.setForeground(new Color(153,153,255));
//            txtYAxis.setText("YAXIS");
//            
//            txtWidth.setFont(new Font("Segoe Print", Font.ITALIC, 16));
//            txtWidth.setForeground(new Color(153,153,255));
//            txtWidth.setText("WIDTH");

        
        repaint();
        panelRegister.repaint();
        }
        }
    }//GEN-LAST:event_txtZAxisKeyPressed

    /**
     * @param args the command line arguments
     */
    
    //      COLOR CODE
//0: Black
//1: Blue
//2: green
//3: cyan
//4: red
//5: Magenta
//6: Light Gray
//7: darkgray
//8: yellow
//9: white
//10: Organge
//11: pink
//12: Gray
//13: Browns
//14: Nước biển
//15: Màu mây
//16: Dòng chảy
//17: NÚI TÔNG NHẸ 2
//18: NÚI TÔNG NHẸ 1
//19: NÚI TÔNG NHẸ 0
//20: MÀU NẮNG    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
         DrawingAlogithrm a=new DrawingAlogithrm();
         Graphics2D g2=(Graphics2D)g;
         a.DrawAxis3D(500, 300, g);
         a.HinhCau( x, y, z, w, color, g);    
     }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sphere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sphere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sphere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sphere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sphere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAdd;
    public javax.swing.JComboBox<String> cbColor;
    public javax.swing.JLabel lbAdd;
    private javax.swing.JLabel lbColor;
    public javax.swing.JPanel panelRegister;
    public javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtMinimize;
    public javax.swing.JTextField txtRadius;
    public javax.swing.JTextField txtXAxis;
    public javax.swing.JTextField txtYAxis;
    public javax.swing.JTextField txtZAxis;
    // End of variables declaration//GEN-END:variables
}
